### ISSUE TITLE
Selector Stats tab now appears in Edge 123, but is empty

### ISSUE THREAD

**Issue by saraheagle** [MicrosoftEdge/DevTools#229] opened 2024-02-20 09:28 UTC
Following on from this issue, https://github.com/MicrosoftEdge/DevTools/issues/223
I downloaded and installed Edge Canary.

Sometimes the Selector Stats tab shows, but there is no information showing.
See https://screenpal.com/watch/cZnYQ0VdSiK

Microsoft Edge
Version 123.0.2414.0 (Official build) canary (64-bit)

Thanks
S :)

**Comment by captainbrosset** [comment] 2024-02-20 10:31
Sorry to hear that. I just tested locally and the feature worked great for me. So maybe this is due to the particular app you are profiling. Any chance you could share a URL to the app, so I can try to repro?

**Comment by ArtjomsFomins** [comment] 2024-02-23 09:08
I have something similar. I today updated Microsoft edge and the selector tab just disappeared.
Version 121.0.2277.128 (Official build) (64-bit)
Ubuntu 20.04
![image](https://github.com/MicrosoftEdge/DevTools/assets/126476500/df1bcced-5f8b-4ecf-9b5d-0ed5cd7d425f)

**Comment by captainbrosset** [comment] 2024-02-26 10:04
@ArtjomsFomins yes, unfortunately this is a known problem with Edge 121 that got resolved later in Edge 123 (which will get released on March 21st). This problem was tracked in issue #223.

This present issue, however, is for a case where the Selector Stats tab sometimes doesn't work with Edge 123.

**Comment by captainbrosset** [comment] 2024-02-28 08:59
@saraheagle any chance you could share more details about your particular scenario. So far, we haven't been able to reproduce the issue in Edge 123. Does it only occur with one particular webpage? Only on your computer? Which OS is this? Any extra information you can provide would help a lot.

**Comment by saraheagle** [comment] 2024-02-28 09:51
Sorry - it is because I was using a preproccesor and its local server. Once you asked for a URL, I twigged why!
On another site I was having issues on only some "Recalculate Styles", but I haven't had time to test that properly, so if I do have issues with that I will create a new post. Thank you so much for your quick reply.
S :)

**Comment by captainbrosset** [comment] 2024-03-01 09:59
Ok that sounds great. I'll close this issue for now. Do feel free to create a new one if you ever encounter a new issue.

**Closed as completed by captainbrosset** 2024-03-01 09:59 UTC
Labels: bug, more info needed
