### ISSUE TITLE
Class private property evaluates as undefined in the Console in Edge, but not in Chrome

### ISSUE THREAD

**Issue by datvm** [MicrosoftEdge/DevTools#259] opened 2024-06-12 10:33 UTC
Please see [this question here on Microsoft Learn](https://learn.microsoft.com/en-us/answers/questions/1693543/js-variable-assigned-a-value-is-always-undefined-i?page=1) where it's confirmed it is apparently a bug in Microsoft Edge.

I am encountering an issue where a variable is assigned a value, but the value is always `undefined` in Microsoft Edge. Strangely, the same code works as expected in Google Chrome. I have confirmed the assigned value is not `undefined`, and checked that the code does not have any way to assign `undefined` to the variable. Even though hovering over the variable in DevTools shows the correct value, evaluating the variable in the console still results in `undefined`. Here is the relevant code:

![image](https://github.com/MicrosoftEdge/DevTools/assets/6388546/414405fb-6735-4726-9428-e9f52dc0e9e5)

```js
customElements.define("popup-page", class extends HTMLElement {
    // ...
    #lastDownload = 0;
    // ...

    async #download() {
        // ...
        this.#lastDownload = 0;
        // ...

            for (let i = 0; i < urls.length; i++) {
                // ...
                const id = el.downloadId = await this.#attemptItemAsync(url, maxCon, addDelay);
            }
    }

async #attemptItemAsync(url, maxCon, addDelay) {
        try {
            if (addDelay > 0) {
                const now = Date.now();
                if (now - this.#lastDownload < addDelay) {
                    await sleepAsync(now - this.#lastDownload);
                }
                this.#lastDownload = now;
            }
            
            // ...
        }
        catch {
            return;
        }
    }
});
```

I believe this is a bug in Microsoft Edge. When I sideloaded the same extension into Google Chrome, the bug did not occur. Please let me know if you need more information.

AB#52257933

**Comment by captainbrosset** [comment] 2024-06-17 13:12
Thank you for reporting this here. I have two questions:

1. Does the bug only appear in the DevTools Console? That is: the value appears as `undefined` in the Console, but the code works.
2. Are you able to provide a full code snippet for us to try and reproduce this locally? Right now, the code is incomplete and I can't really run it locally without inventing other parts of the code, which might not be the right ones to reproduce the issue.

Thank you.

**Comment by datvm** [comment] 2024-06-17 16:45
@captainbrosset  Hi,

1. No, the DevTool tooltip is the only place where the should-be value shows up. However, the "real" value is still `undefined`, making my `if` statement's expression `false` when it should be `true`. That is, the code doesn't perform as it should.

2. I sent it to the person at [this post](https://learn.microsoft.com/en-us/answers/questions/1693543/js-variable-assigned-a-value-is-always-undefined-i?page=1) privately because it's a private project. Unfortunately I am not sure what causes it and cannot make a minimal reproducible example. If you provide a private channel I will send over the file.

**Comment by captainbrosset** [comment] 2024-06-27 07:36
@datvm if you can, please send the file over as a private message either on my twitter or mastodon account, which are linked to from my github account page: https://github.com/captainbrosset/
Or send it as an email: patrickbrosset at gmail dot com.

**Comment by datvm** [comment] 2024-06-28 07:20
@captainbrosset thanks, sent you an email.

**Comment by captainbrosset** [comment] 2024-07-03 10:04
Thank you @datvm. It took me a bit of time, but I did find a reduced test case. This has nothing to do with your specific extension code, but instead seems to be a bug with the way DevTools evaluates private properties.

Here is the reduced test case:

```html
<!DOCTYPE html>
<script>
class Foo {
  #bar = 1;
  constructor () {
    console.log(this.#bar);
    debugger;
  }
}

new Foo();
</script>
```

When you run this, the console shows `1`, as expected, because of the `console.log` statement. Also, hovering over the `this.#bar` expression in the **Sources** tool shows the right value. But, when evaluating `this.#bar` in the **Console** tool, the result is `undefined`. See below:

<img width="329" alt="image" src="https://github.com/MicrosoftEdge/DevTools/assets/1152698/7761936e-6c75-4d7e-bcd8-041f60700173">

I was also able to verify that this worked fine in Chrome, just not in Edge.

I'll bring this up with our dev team and make sure the bug is tracked on our backlog. Thank you for filing.

**Comment by datvm** [comment] 2024-07-04 02:15
@captainbrosset Hi, thank you for the info. Please note that in your code, the issue only happens to the printed out Console, however, in my extension code, **the whole expression actually gets evaluated incorrectly**. For example, I added an `if` statement to your code:

```
class Foo {
  #bar = 1;
  constructor () {
    console.log(this.#bar);
    if (this.#bar < 2) {
    	console.log("< 2");
    }
    debugger;
  }
}

new Foo();
```

In the above code, the `if` expression is still evaluated correctly and `< 2` is printed out even though `this.#bar` is printed out as `undefined`. In my extension code, the whole `if` statement is skipped due to `undefined` being falsy.

**Comment by captainbrosset** [comment] 2024-07-04 08:13
That is very surprising. If there's indeed an issue with the running code (whether DevTools is opened or not), then that is a different bug with the V8 scripting engine. What's surprising is that we use the exact same as Chrome does. So I don't expect there to be any differences.

Note that the DevTools bug (`undefined` showing up in the Console) is being investigated by our dev team, and they've identified the root cause.

I suggest waiting for a fix to make it to the next Edge Canary, and then test again to see if your issue goes away.

**Comment by datvm** [comment] 2024-07-04 10:05
@captainbrosset _Maybe_ an issue when the method is `async`? As for my extension, the code in question is this:

```
  if (now - this.#lastDownload < addDelay) {
      await sleepAsync(now - this.#lastDownload);
  }
```

In Edge, my tasks all ran at the same time without delay (that's why I used DevTools to inspect the issue to begin with). I am 90% sure the issue happens without DevTools being opened.

In Chrome, the tasks are correctly delayed.

**Comment by captainbrosset** [comment] 2024-07-12 13:13
@datvm would you have time to test something please?
Our dev team tells me they've addressed the bug where the value appears as undefined in the Console.
So, if you have some time, please make sure you have Microsoft Edge Canary 128.0.2706.0 (or later) and test your scenario again.
I'm curious to learn how it impacts your issue.

**Comment by datvm** [comment] 2024-07-13 10:47
Hi just tested on Edge Canary 128.0.2709. Everything looks good including the code logic.

**Comment by captainbrosset** [comment] 2024-07-15 08:22
Great to hear. Thanks for testing. Closing this issue now.

**Closed as completed by captainbrosset** 2024-07-15 08:22 UTC
Labels: bug, tracked
