### ISSUE TITLE
[Focus mode]White screen for debugging background JavaScript(i.g. service worker) of extensions

### ISSUE THREAD

**Issue by xiaofeihan1** [MicrosoftEdge/DevTools#86] opened 2022-08-01 07:26 UTC
Hi, Team,
I can not debug background javascript of extensions in focus mode, as shown below. I thought it is a bug.
In manifest v3 extensions, it needs a service worker as background JavaScript. When focus mode feature is open, the bug will re-produce. After I close the feature, I can debug normally.
<img width="739" alt="image" src="https://user-images.githubusercontent.com/107654914/182095016-d678f5a9-e225-4e00-8875-2ea356141ead.png">

[AB#40714690]

**Comment by captainbrosset** [comment] 2022-08-01 08:00
Thank you for filing this. I was able to reproduce too. With Focus Mode, debugging service workers doesn't work (blank window), without Focus Mode, it works fine.
I'll add this to the team's radar so it can get fixed asap.

**Comment by captainbrosset** [comment] 2022-08-01 15:44
Well, it looks like this is already fixed! I tested in a recent version of Edge Canary and the bug is now gone.
It apparently got fixed in 105.0.1329.0, so you'll need at least this version for it to work again.

Thanks again for reaching out about this.

**Closed by captainbrosset** 2022-08-01 15:44 UTC
Labels: bug, tracked
