### ISSUE TITLE
Unable to access 3D view

### ISSUE THREAD

**Issue by crrobinson14** [MicrosoftEdge/DevTools#186] opened 2023-10-02 17:58 UTC
While using Edge to debug a Teams Tab App (as started automatically by the Teams Toolkit from VSCode) on a Mac (M1) I receive the following error. But there appears to be no way to identify or install whatever components are "missing". I am definitely connected to the Internet.

![image](https://github.com/MicrosoftEdge/DevTools/assets/1675563/6fb26735-e56a-482d-9abe-6c6f76a9b21c)

AB#46958989

**Comment by captainbrosset** [comment] 2023-10-03 08:00
Oh that's weird. Thanks so much for filing this. I will make sure this is being tracked by the dev team.
In the meantime, have you tried closing and re-opening DevTools and see if that forced the downloading of the missing component? Also, is there an info banner appearing just above DevTools about this?

**Comment by crrobinson14** [comment] 2023-10-03 13:45
@captainbrosset Restarting DevTools doesn't seem to resolve it for me (by which I assume you mean the reset/restart button in DevTools prefs). But I have the same experience you do where Composited Layers does appear to have some entries in it:

![image](https://github.com/MicrosoftEdge/DevTools/assets/1675563/055887a1-1900-4244-9c07-364a3d837246)

Happy to test anything else you like since I can reproduce this 100%.

**Comment by captainbrosset** [comment] 2023-10-04 08:17
Thanks @crrobinson14 for the detail. Our team is looking into this. We'll let you know of any questions we have and when we have a fix coming.

**Comment by mtbayley** [comment] 2023-10-04 13:20
I have also been running into this for several months now

![image](https://github.com/MicrosoftEdge/DevTools/assets/34929316/06ec3701-9616-48a0-8f32-f5caec289298)

**Comment by captainbrosset** [comment] 2023-10-11 07:27
For information, we have 2 fixes on the way for this:

1. The message will be made a bit clearer. The 3D view is a component that's not built-in to Edge. It's only downloaded on-demand, the first time you use the 3D view. So you do have to close and re-open DevTools the first time, for it to work. The first fix is about making the message more clearly explain this.
2. The DOM and z-index tabs appear frozen, only the Composited Layers tab works at the moment. We have this bug tracked as well, and are working on a fix for this regression.

Thanks for your patience!

**Comment by vidorteg** [comment] 2023-11-09 23:42
Hi everyone, 

We put out a couple of fixes for the issues mentioned in here:
  1. The message is shown whenever some of the Devtools components need to be updated/reloaded. We modified the message to make it more clear including steps on how to fix it.
  2. We fixed the issue and Z-Index and DOM should be working again.

both fixes should make its way to Edge Canary soon and then to the rest of the channels, thank you for the report.

**Closed by vidorteg** 2023-11-09 23:42 UTC
Labels: bug, tracked

**Comment by huebnerr** [comment] 2023-12-21 02:46
Thank you very much. I'm attempting to debug a Z-indexing issue and was confused why the other Z-index and DOM seemed to be frozen.

**Comment by captainbrosset** [comment] 2023-12-21 09:54
> Thank you very much. I'm attempting to debug a Z-indexing issue and was confused why the other Z-index and DOM seemed to be frozen.

Do the z-index and DOM tab work for you now? They used to be broken before, but this bug should now be gone. Let us know if you still have an issue.

**Comment by vanowm** [comment] 2024-01-22 02:55
When Edge is launched from VSCode debugger, `3D View` is not available.

Here is a command line used to launch Edge:
```
"C:\Users\Dev\AppData\Local\Microsoft\Edge SxS\Application\msedge.exe" --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-renderer-backgrounding --disable-sync --metrics-recording-only --no-first-run --no-default-browser-check "--user-data-dir=e:\Program Files\VSCode\data\user-data\User\workspaceStorage\f8081997708878520f20c6fb314afe8f\ms-vscode.js-debug\.profile" --auto-open-devtools-for-tabs about:blank --remote-debugging-pipe
```

The issue here is `--disable-default-apps` flag. If Edge was launched with this flag just once, there is something left in the profile which prevents `3D View` to initialize even after edge was launched without that flag.
The only way to bring `3D View` back is to launch Edge without `--disable-default-apps` and `--disable-background-networking` flags. After that, we can add back `--disable-background-networking` flag and '3D View` will still work.

**Comment by captainbrosset** [comment] 2024-01-22 09:55
Thanks for posting. I moved this to a new issue since it might be a different problem, and since this issue is now closed.

**Comment by NkmGlobal** [comment] 2024-02-19 19:51
> Thanks for posting. I moved this to a new issue since it might be a different problem, and since this issue is now closed.

Im facing this same challenge. Any update on fixes?

> > Thank you very much. I'm attempting to debug a Z-indexing issue and was confused why the other Z-index and DOM seemed to be frozen.
> 
> Do the z-index and DOM tab work for you now? They used to be broken before, but this bug should now be gone. Let us know if you still have an issue.

**Comment by captainbrosset** [comment] 2024-02-20 10:33
No, unfortunately no update on that specific issue. If you have new information to share about it, could you please provide it in issue #212? The more information we have to reproduce and debug the problem, the better. Thank you.

**Comment by simonziegler** [comment] 2025-03-01 10:55
I have had this issue for some months and nothing I can find online to resolve it work.

**Comment by HunterAhlquist** [comment] 2025-06-09 18:15
I'm having this issue when running a visual studio 2022 instance of Edge. (debug mode)

**Comment by devbf** [comment] 2025-09-17 11:01
I'm also not able to get the 3D view running in the developer Edge instance which is started by Visual Studio.
Copying the URL of the developer server to my native instance of Edge makes it possible to use the 3D view.
