### ISSUE TITLE
New Edge version 125, DevTools - Application tab make browser crash

### ISSUE THREAD

**Issue by GangDEV** [MicrosoftEdge/DevTools#255] opened 2024-05-18 21:04 UTC
Just updated to the new 125 version, doing my normal development work, opened the DevTools, went to "Application" tab, then the Edge browser crashed.

Rollback to version 124.0.2478.109, the browser is not crashing anymore.

Steps to reproduce:

1. Create an app with a web app manifest that defines an icon with no size property.
1. Run the app in Edge 125 or 126.
1. Open DevTools.
1. Open the Application tool.

Result: Edge hangs for a few seconds and then crashes.

AB#51532435

**Comment by captainbrosset** [comment] 2024-05-24 16:39
Sorry about this. Is this still occurring for you? Does it always happen on the same webpage, or on all webpages?
If it's always on the same one, it would help us so much if you could create a minimal reproduction webpage (or just provide the URL if it's a public one).

**Comment by hlhr202** [comment] 2024-05-30 10:07
same thing. but i guess chrome also experience the same bug.

**Comment by hlhr202** [comment] 2024-05-30 10:15
BTW, the issue doesn't exist in canary chrome.

**Comment by GangDEV** [comment] 2024-05-31 12:31
sorry for the delay for providing more info, but good news is our development team has figured out what was the problem. it was because of in the web manifest file, one of the icons item was missing the "sizes" property, after specified the "sizes" property, even put wrong size info, the Edge browser is not crashing anymore.

again this is only happens on Edge browser version 125. rollback to version 124 also not crashing. Chrome browser working fine.

@captainbrosset

**Comment by captainbrosset** [comment] 2024-06-03 08:26
@GangDEV thank you for responding, and even more for figuring out the exact steps that make it crash.
I was able to confirm locally:

* Create an app with a web app manifest that defines an icon with no `size` property.
* Run the app in Edge 125 or 126.
* Open DevTools.
* Open the Application tool.

Result: Edge hangs for a few seconds and then crashes.

**Comment by captainbrosset** [comment] 2024-06-03 08:27
I will make sure our dev team sees and prioritizes this.

**Comment by captainbrosset** [comment] 2024-06-03 08:30
> same thing. but i guess chrome also experience the same bug.

Yeah, I was also able to reproduce this in Chrome. Filed this upstream issue: https://issues.chromium.org/issues/344343046

**Comment by captainbrosset** [comment] 2024-06-07 09:29
My issue got closed as a duplicate of [341319146](https://issues.chromium.org/issues/341319146) where a fix has been made! So this issue will go away soon.

**Closed as completed** 2024-12-02 21:55 UTC
Labels: bug, tracked, upstream issue
