### ISSUE TITLE
Devtools cannot group JS files by folder on windows

### ISSUE THREAD

**Issue by mpaliath** [MicrosoftEdge/DevTools#60] opened 2022-06-01 00:44 UTC
When debugging on windows, the files are not grouped by folder names which is a huge pain as our project contains hundreds of files. After some searching, the underlying issue is fixed in chromium per https://github.com/nodejs/node/issues/15477

Can you please port the fix to edge dev tools as well?

**Comment by captainbrosset** [comment] 2022-06-01 09:49
Thanks for reaching out @mpaliath.

This is odd because the [fix for this](https://chromium-review.googlesource.com/c/chromium/src/+/828466) seems to have been done in Chromium in 2018. Edge is based on Chromium, and so the fix should be there too.

I tried today on windows 11, with a local nodejs project I'm working on, and here is what I see in devtools:

<img width="346" alt="screenshot of edge devtools, showing the sources panel, connected to a nodejs process" src="https://user-images.githubusercontent.com/1152698/171376996-b7933074-24fa-4896-907d-95e0a558b6d8.png">

As the screenshot shows, the files are grouped by folder as usual.

If you are seeing something different, please do share your exact steps to reproduce, and a screenshot of what is happening.

**Comment by captainbrosset** [comment] 2022-08-03 08:36
This has been opened for 2 months and we haven't received more information from you on this. So I'll go ahead and close the issue for now.

**Closed by captainbrosset** 2022-08-03 08:36 UTC
Labels: bug, more info needed
