### ISSUE TITLE
Network Console - Post Body stuck on loading

### ISSUE THREAD

**Issue by llowevad** [MicrosoftEdge/DevTools#228] opened 2024-02-16 16:38 UTC
Cannot do a post body as it is stuck on loading... also stuck on loading is a Get response body

Version: 121.0.2277.128 (Official build) (64-bit)

<img width="297" alt="image" src="https://github.com/MicrosoftEdge/DevTools/assets/8823690/90e93232-6c04-4208-9c74-22642bc23041">

**Comment by hj8e45** [comment] 2024-02-20 03:38
same issue, same version

**Comment by captainbrosset** [comment] 2024-02-20 10:35
Sorry about this. We're aware that this experimental tool is currently broken. See #224 and #227. I'll close this issue as it's very likely due to the same root cause.

**Closed as completed by captainbrosset** 2024-02-20 10:35 UTC
Labels: bug

**Comment by hussainih** [comment] 2024-04-24 03:14
I encountered similar issue. I believe when you switch to Raw text the console needs to download something to display the body area, not sure about that. However, the issue was resolve when I disconnected from VPN. We have Zscaler the blocks some request.
