### ISSUE TITLE
Unminify performance profile should use sourcemaps from Symbol Server

### ISSUE THREAD

**Issue by zoherghadyali** [MicrosoftEdge/DevTools#8] opened 2022-03-08 00:11 UTC
In Microsoft Edge 99, the Unminify button was added to the Performance tool which uses sourcemaps hosted side-by-side with production code to create an unminified version of a recorded performance profile. If developers have already set up Azure Artifacts Symbol Server to host their sourcemaps, the Performance tool should be able to use them to unminify a performance profile. Doing so would remove the requirement that you have to host your sourcemaps side-by-side with your production code like this:
<img width="206" alt="unminify-perf-profile-sourcemaps msft" src="https://user-images.githubusercontent.com/34316555/157139801-81a556d0-b0f0-4da2-9ffa-501e5cc842fc.png">

**Comment by captainbrosset** [comment] 2022-03-10 13:23
This seems to be a duplicate of #15 so I will close this issue now.

**Closed by captainbrosset** 2022-03-10 13:23 UTC
Labels: feature
