### ISSUE TITLE
"Edit and Resend" feature is not working

### ISSUE THREAD

**Issue by JoernBerkefeld** [MicrosoftEdge/DevTools#224] opened 2024-02-09 08:55 UTC
**Update**: This issue is used to track all Network Console problems.

* "Edit and Resend" option does not allow to see or edit the body
  * https://github.com/microsoft/edge-devtools-network-console/issues/89
* https://github.com/MicrosoftEdge/DevTools/issues/227
* https://github.com/MicrosoftEdge/DevTools/issues/228
* https://github.com/microsoft/edge-devtools-network-console/issues/125
* https://github.com/microsoft/edge-devtools-network-console/issues/72
* https://github.com/microsoft/edge-devtools-network-console/issues/127
* https://github.com/microsoft/edge-devtools-network-console/issues/129
* https://stackoverflow.com/questions/78273237/microsoft-edge-edit-and-resend-not-showing-up

AB#48918362

**Comment by captainbrosset** [comment] 2024-02-09 09:29
Thanks so much for reaching out and filing this. I'll make sure this is tracked and investigated by our team.

**Comment by pabloui** [comment] 2024-04-03 11:03
Network console tab not opening from edit and resend option. Any plan to get it resolved ?

**Comment by bugzorc** [comment] 2024-04-05 16:59
> Network console tab not opening from edit and resend option. Any plan to get it resolved ?

Not working for me too

**Comment by 3wheel** [comment] 2024-04-19 08:58
Same here; Edit/Resend doesn't work and it hinders our security trainings.
Any EAT on a fix?

**Comment by troilus** [comment] 2024-04-22 02:12
Still not working in 125.0.2518.0

**Comment by captainbrosset** [comment] 2024-04-22 13:46
Sorry about the inconvenience. No estimated time to fix that we can share yet.

**Comment by Yhxang** [comment] 2024-04-25 04:43
在开发者工具设置选项里切换回旧版DevTools UI，然后添加网络控制台工具后，可暂时解决这个问题

**Comment by rivancic** [comment] 2024-04-26 14:08
Doesn't work for me either.

**Comment by JWess** [comment] 2024-04-30 20:31
As a developer, this is a differentiating feature between Edge and Chrome. Without it, I've switched back to Chrome.

**Comment by captainbrosset** [comment] 2024-05-03 13:12
Sorry to hear. However, Correct me if I'm wrong though, Chrome doesn't have this, right?

**Comment by JWess** [comment] 2024-05-03 14:38
> Sorry to hear. However, Correct me if I'm wrong though, Chrome doesn't have this, right?

You are correct, but I use Chrome for everything non-development, and this was the main reason I had switched to Edge for development. Without it, it didn't make sense to use two browsers.

**Comment by opnil** [comment] 2024-05-05 10:31
> > Duyduğumuz için üzgünüz. Ancak yanılıyorsam düzeltin, Chrome'da bu yok, değil mi?
> 
> Haklısın, ancak geliştirmeyle ilgili olmayan her şey için Chrome'u kullanıyorum ve geliştirme için Edge'e geçmemin ana nedeni de buydu. O olmadan iki tarayıcı kullanmanın bir anlamı yoktu.

+1

**Comment by alunmj** [comment] 2024-05-25 00:11
Really want to see this feature working. It's an important part of basic security testing, and while I can achieve the same effects with web proxies, they're ... fiddly. It's much more handy to have this basic ability built in to the browser.

**Comment by Blaklis** [comment] 2024-05-25 16:26
Might be worth to bump a bit the priority on this one. This is definitely a problem, I second @alunmj with it.

**Comment by srujalvcon** [comment] 2024-05-27 08:51
I agree, I switched to edge just because of the same reason.

It helps me debug my API's quickly with different parameters.

Please bump up its priority @captainbrosset.

**Comment by Ryanb58** [comment] 2024-05-27 18:02
Bump this. Also running into this issue on my Intel MBP. Replay XHR works. Edit & resend does not.

**Comment by captainbrosset** [comment] 2024-05-28 19:25
We have a fix ready for this in 126 (currently in beta, and will become stable in mid June).
Thank you for your patience. If folks here want to test with beta or canary, please go ahead and let me know if things work for you.
Otherwise, please wait a couple of more weeks for the fix to be available in stable.

**Comment by bugzorc** [comment] 2024-05-28 19:43
Let me see

**Comment by bugzorc** [comment] 2024-05-29 07:13
Tested it on the canary version, working pretty good, haven't found any problems with it up to now, truly appreciate it.

**Comment by captainbrosset** [comment] 2024-05-29 13:31
Great to hear. Let's give it a little time before closing this, but seems like this should be resolved now.

**Comment by GFKSolar** [comment] 2024-05-31 20:20
it started to work again for like 2 weeks and now it suddenly dont work again... whats happening.. is there any workaround? to make it show up again?

**Comment by Cfun1** [comment] 2024-06-02 00:11
Great news that this feature is fixed and coming back. It is a very helpful and handy tool that allows to mock parameters for quick API testing.

**Comment by toupswork** [comment] 2024-06-13 07:04
I am a Full Stack Software Engineer, and the ONLY reason I switched to Edge after using Chrome for 16 years is for the Edit and Resend. I used it all day every day until it stopped working a few months back. I can not express to you how critical this feature is to my job. I have even persuaded the other devs on my team to switch to Edge because of it. I am sure there are tons of other people out there who share this sentiment but have not commented on here.

Your PO should really consider bumping up the priority of this defect. This is crippling a lot of developers.

**Comment by bugzorc** [comment] 2024-06-17 10:22
> I am a Full Stack Software Engineer, and the ONLY reason I switched to Edge after using Chrome for 16 years is for the Edit and Resend. I used it all day every day until it stopped working a few months back. I can not express to you how critical this feature is to my job. I have even persuaded the other devs on my team to switch to Edge because of it. I am sure there are tons of other people out there who share this sentiment but have not commented on here.
> 
> Your PO should really consider bumping up the priority of this defect. This is crippling a lot of developers.

I think you should have read the comments above, the feature is coming back soon, a hail edge browser

**Comment by captainbrosset** [comment] 2024-06-17 13:01
I just tested in 126, which is now available in the stable channel, and confirmed that the feature was working. 
Closing this issue. Thanks everybody.

**Closed as completed by captainbrosset** 2024-06-17 13:01 UTC
Labels: bug, tracked

**Comment by tranthinhqnam** [comment] 2024-07-12 08:55
Thanks team

**Comment by tranthinhqnam** [comment] 2024-07-12 09:18
Omg, i think you and team dont check UI, font and homogeneous, it's so ....speechless

**Comment by ghost** [comment] 2024-07-25 05:06
Can't work in 127.0.2651.61
(404 not found)

**Comment by rivancic** [comment] 2024-08-09 07:00
Close the issue to open another one. At least its good for Sprint velocity.

**Comment by toupswork** [comment] 2024-08-09 17:19
> Can't work in 127.0.2651.61 (404 not found)

You do realize that's not a valid IP address, right?

**Comment by RemMai** [comment] 2024-09-26 02:31
> 我刚刚在 126 中进行了测试，现在在 stable 频道中可用，并确认该功能正在运行。关闭此问题。谢谢大家。

hi, my edge version is  129.0.2792.52, The network console still shows a 404 unavailable status, and I don't think this issue has been well resolved.

**Comment by Cfun1** [comment] 2024-09-26 18:38
@RemMai  #224 was fixed at that time, then this feature got broken again, I believe it is tracked in this opened issue https://github.com/MicrosoftEdge/DevTools/issues/268
