### ISSUE TITLE
[JSON Viewer] Find in page not working for long json objects

### ISSUE THREAD

**Issue by kebeabap** [MicrosoftEdge/DevTools#183] opened 2023-09-22 08:26 UTC
Having a long json with a total of tens of thousands of lines rendered out, the built-in search of the Edge-browser won't find all search terms. 
My example json has (rendered) >60k lines
A search term in line 33000 is not found, when I press ctrl+f in Edge.
Using Version 116.0.1938.69 (Official Build) (64-Bit) / not using any other json rendering extensions.

Disabling json-viewer stops rendering of the request result, but therefore, find in page works again and reveals the search term.

**Comment by captainbrosset** [comment] 2023-09-22 08:36
Thanks for your report. This is a known issue and we've got somebody working on it at the moment.
Hoping to have a fix for it deployed soon! 
I'll close this as a duplicate of #87 as the issue was already reported there. Feel free to watch that issue for updates on this.

**Closed by captainbrosset** 2023-09-22 08:36 UTC
Labels: bug

**Comment by ghost** [comment] 2024-04-03 08:01
I have to search long json files quite often. So I disabled edge-json-viewer. Since the last edge update it is not possible anymore (https://github.com/MicrosoftEdge/DevTools/issues/238). Frustrating...

**Comment by captainbrosset** [comment] 2024-04-03 12:49
Sorry about this, disabling the JSON Viewer will soon be possible again.

That said, the JSON Viewer now has a better search which should work on long JSON objects. Click somewhere in the JSON, and then press `Ctrl+F`. You should see the new search tool:

![image](https://github.com/MicrosoftEdge/DevTools/assets/1152698/26a14edd-159c-4560-afba-57e896206fc6)
