### ISSUE TITLE
Where did horizontal scrollbar go?

### ISSUE THREAD

**Issue by muchqs** [MicrosoftEdge/DevTools#299] opened 2024-11-29 18:36 UTC
https://i.imgur.com/ffbL1ca.jpg

I was on v127.0.2651.86 and it had horizontal scrollbar. Updated to v131+ and it's not there anymore?

AB#55325310

**Comment by leahmsft** [comment] 2024-12-02 18:24
Thanks for reporting this. I'll add this to the engineering team's backlog for consideration.

**Comment by leahmsft** [comment] 2024-12-02 21:59
Filed a bug upstream: https://issues.chromium.org/issues/381908894

**Comment by leahmsft** [comment] 2024-12-04 17:27
@muchqs got an update back from upstream: 

> Status: Won't Fix (Intended Behavior)
This is working as intended - the scrollbar is missing nowadays due to the new design, but you can see the full path name by hovering over the path (tooltip).

Closing now as won't fix.

**Closed as not planned by leahmsft** 2024-12-04 17:27 UTC
Labels: bug, tracked

**Comment by muchqs** [comment] 2024-12-05 06:52
@leahmsft 

Thanks. But the argument that a hover tooltip is better and can replace a scrollbar is absolutely crazy.

Imagine a few URLs that all look similar, with only a few characters at the end that's different. In the older version, I can just drag the scrollbar to the right to scroll to the end of the line to see the difference, now I have to hover mouse over each line, wait for the tooltip to appear, memorize each one, then compare them in my head. How is that good user experience?

Let's see an example:

Please look at the line I want, and the other lines near it. They all look similar at quick glance right?
https://i.imgur.com/tCkKIeW.png

Now look at them again when I scroll all the way to the end. See how the line I want is shorter than the other lines? I can spot it immediately at a quick glance because the scrollbar is available.
https://i.imgur.com/lEqtllu.png

Now look at a video of this in action. Can you quickly spot the line I want just from hover tooltips? I don't think so.
https://i.imgur.com/3V8c080.mp4

Plus, why remove something useful like this when it's not a problem?? Just for the sake of **_looks_**?? Seriously?

**Comment by leahmsft** [comment] 2024-12-05 17:15
@muchqs I understand your frustration with the recent change. I encourage you to share this feedback directly with upstream to help them consider improvements. You can provide feedback on the bug here: https://issues.chromium.org/issues/381908894 Thank you.
