### ISSUE TITLE
How can I jump directly to vscode after clicking on a file in the console of devtools?

### ISSUE THREAD

**Issue by Tera-ravyn** [MicrosoftEdge/DevTools#263] opened 2024-07-18 03:42 UTC
I had previously succeeded in opening the file directly in visual studio code by clicking on the file name directly in devtools. But now for some reason I can't do that anymore. I can confirm that I have linked to the source file and that changes in devtools can be synchronized to the local file; however, none of the filenames in the console have a link icon, and clicking on them still opens the file within devtools, and does not evoke the corresponding file to be opened in visual studio code.
It looks all fine in workspace, I'm not sure where the problems are.
![image](https://github.com/user-attachments/assets/ed5cb08d-c031-4ae7-96a7-0970e79408bb)
![image](https://github.com/user-attachments/assets/04cd149c-3b45-4e0b-b9ec-8df4989150ea)

**Comment by captainbrosset** [comment] 2024-07-19 09:29
This sounds like a bug. In fact, I believe this might be a duplicate of #143. So closing this one in favor of that other one. Thank you for reporting.

**Closed as completed by captainbrosset** 2024-07-19 09:29 UTC
Labels: feedback
