### ISSUE TITLE
控制台自动完成列表位置异常

### ISSUE THREAD

**Issue by baiej214** [MicrosoftEdge/DevTools#108] opened 2022-09-30 09:15 UTC
![image](https://user-images.githubusercontent.com/683351/193236699-9ae2ea55-5e18-48f9-8851-285af3450bf3.png)

![image](https://user-images.githubusercontent.com/683351/193236958-6ce5a512-75fe-4e6c-b540-c47ed7c07aa2.png)

![image](https://user-images.githubusercontent.com/683351/193237112-d58403a0-154c-48c6-9519-5cad99a12cf5.png)

**Comment by captainbrosset** [comment] 2022-10-03 07:39
Thank you for reporting this issue. As far as I understand, this is about the Console auto-complete which is missing in 105.
This is unfortunately a known bug in this release, and we have a fix coming up for it in 106. Edge 106 should be rolled out to everyone as an update today, October 3, 2022.
I'll close this issue for now, but please check once you have 106 if the issue is indeed fixed for you. If not, please comment here and we can re-open it.

**Closed by captainbrosset** 2022-10-03 07:39 UTC
Labels: bug
