### ISSUE TITLE
Breakpoints assigned to wrong line in Typescript file.

### ISSUE THREAD

**Issue by mattjacobsen** [MicrosoftEdge/DevTools#106] opened 2022-09-23 08:10 UTC
Hello,

![breakpointsbroken](https://user-images.githubusercontent.com/1132938/191917136-9a9de232-1146-47ba-8e7f-cb2921476eb6.gif)

I've cleared "site data" in the Applications tab (and cleared things manually - no serviceworker, no cache storage, nothing). The debugger is showing the newest version of both the TS and JS source. It looks as if the sourcemaps aren't correct but if I view the same site in Firefox (with the same source and sourcemaps) then everything works out ok.

Any ideas?

Many thanks,
Matt

**Comment by captainbrosset** [comment] 2022-09-26 14:09
Thanks for reaching out. By any chance, could you check if this also happens in Chrome? I know there's been a lot of recent changes done in the debugger in the chromium project, so I have a feeling like this might be due to that.

**Comment by mattjacobsen** [comment] 2022-09-27 07:43
Hi,

I've just tried it again in both Edge (Windows 105.0.1343.50) and Chrome (Windows 105.0.5195.127) - which I downloaded specifically to test as I exclusively use Edge/Firefox/Safari for day to day work - and everything currently seems to be behaving itself in both browsers. I'll keep bashing at it to see if I can reproduce it again; it has happened a fair few times (in Edge) in the past couple of weeks. 

Also: I also noticed that the tooltips showing a variable's value are also showing up again in Edge. Previously they weren't. It's possible my Edge was updated; unfortunately I didn't note/report the version numbers when filing this issue. Sorry :-|

**Comment by captainbrosset** [comment] 2022-09-27 07:45
No worries at all, and thanks for checking! I know these kinds of bugs are frustrating to reproduce, and sometimes things just seem to work even though they didn't a minute ago.
Please feel free to drop any comments here if you learn anything new about the problem.

**Comment by leahmsft** [comment] 2024-12-02 19:20
Can't repro, closing.

**Closed by leahmsft** 2024-12-02 19:20 UTC
Labels: bug
